name: Build JavKernul

on:
  workflow_dispatch:

env:
  ARCH: arm64
  CC: clang
  CROSS_COMPILE: aarch64-linux-gnu-
  CROSS_COMPILE_ARM32: arm-linux-gnueabi-
  KBUILD_BUILD_USER: "@Java_nih_deks"
  KBUILD_BUILD_HOST: "GitHub-Actions"

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git clang llvm lld build-essential libncurses-dev libssl-dev bc flex bison rsync kmod cpio python3 gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi device-tree-compiler

      - name: Setup DTC Overlay
        run: |
          mkdir -p scripts/dtc
          cp $(which dtc) scripts/dtc/dtc_overlay
          chmod +x scripts/dtc/dtc_overlay

      - name: Build Kernel
        run: |
          make O=out ARCH=$ARCH CC=$CC CROSS_COMPILE=$CROSS_COMPILE rosemary_defconfig
          make -j$(nproc --all) O=out \
            ARCH=$ARCH \
            CC=$CC \
            CROSS_COMPILE=$CROSS_COMPILE \
            CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JavKernul-XianTian-v2.0
          path: |
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/dtbo.img
