name: Build JavKernul

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc build-essential libncurses-dev libssl-dev flex bison rsync kmod cpio python3 device-tree-compiler zip

      - name: Download Proton Clang
        run: |
          git clone https://github.com/kdrag0n/proton-clang.git --depth=1 bin/clang

      - name: Setup DTC Overlay
        run: |
          mkdir -p scripts/dtc
          cp $(which dtc) scripts/dtc/dtc_overlay
          chmod +x scripts/dtc/dtc_overlay

      - name: Build Kernel
        run: |
          export PATH=$(pwd)/bin/clang/bin:$PATH
          make O=out ARCH=arm64 rosemary_defconfig
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            OBJSIZE=llvm-size \
            LD=ld.lld \
            KBUILD_BUILD_USER="@Java_nih_deks" \
            KBUILD_BUILD_HOST="XianTian-CI"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JavKernul
          path: |
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/dtbo.img
